/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404.vue')['default']
    ArrowRightIcon: typeof import('./src/icons/arrow-right-icon.vue')['default']
    BeneficiarioCard: typeof import('./src/components/beneficiario-card.vue')['default']
    BeneficiarioFound: typeof import('./src/components/beneficiario-found.vue')['default']
    BuscarFidelizadoView: typeof import('./src/views/buscar-fidelizado-view.vue')['default']
    BusquedaFidelizado: typeof import('./src/components/busqueda-fidelizado.vue')['default']
    CardIcon: typeof import('./src/icons/card-icon.vue')['default']
    CashIcon: typeof import('./src/icons/cash-icon.vue')['default']
    CheckOkIcon: typeof import('./src/icons/check-ok-icon.vue')['default']
    ChevronDownIcon: typeof import('./src/icons/chevron-down-icon.vue')['default']
    Confirmacion: typeof import('./src/components/confirmacion.vue')['default']
    ExcelIcon: typeof import('./src/icons/excel-icon.vue')['default']
    FileIcon: typeof import('./src/icons/file-icon.vue')['default']
    Finale: typeof import('./src/components/finale.vue')['default']
    FormLabel: typeof import('./src/components/form-label.vue')['default']
    GouIcon: typeof import('./src/icons/gou-icon.vue')['default']
    GowIcon: typeof import('./src/icons/gow-icon.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    InfoPlanes: typeof import('./src/components/info-planes.vue')['default']
    ListadoPagosView: typeof import('./src/views/listado-pagos-view.vue')['default']
    LockIcon: typeof import('./src/icons/lock-icon.vue')['default']
    NequiIcon: typeof import('./src/icons/nequi-icon.vue')['default']
    NoIdIcon: typeof import('./src/icons/no-id-icon.vue')['default']
    PaymentIcon: typeof import('./src/icons/payment-icon.vue')['default']
    PlanCard: typeof import('./src/components/plan-card.vue')['default']
    PreLoader: typeof import('./src/components/pre-loader.vue')['default']
    RegistroView: typeof import('./src/views/registro-view.vue')['default']
    RightIcon: typeof import('./src/icons/right-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SealIcon: typeof import('./src/icons/seal-icon.vue')['default']
    SearchIcon: typeof import('./src/icons/search-icon.vue')['default']
    Stepper: typeof import('./src/components/stepper.vue')['default']
    TablaPagos: typeof import('./src/components/tabla-pagos.vue')['default']
    TitularFound: typeof import('./src/components/titular-found.vue')['default']
    Unauthorized: typeof import('./src/components/unauthorized.vue')['default']
    UserAlertIcon: typeof import('./src/icons/user-alert-icon.vue')['default']
    UserCreate: typeof import('./src/components/user-create.vue')['default']
    UserGroupIcon: typeof import('./src/icons/user-group-icon.vue')['default']
    UserIcon: typeof import('./src/icons/user-icon.vue')['default']
    UserIdIcon: typeof import('./src/icons/user-id-icon.vue')['default']
    UserInfo: typeof import('./src/components/user-info.vue')['default']
    UserNotFound: typeof import('./src/components/user-not-found.vue')['default']
    UserSearch: typeof import('./src/components/user-search.vue')['default']
  }
}
