const SISTEMAS = 20
const TESORERIA = 25
const ADMISIONES = 21
const FACTURACION = 16
const CONTABILIDAD = 24

export {
    SISTEMAS,
    TESORERIA,
    ADMISIONES,
    FACTURACION,
    CONTABILIDAD
}
